{{- if .Values.ingress.enabled -}}
{{- $fullName := include "java-app.fullname" . -}}
{{- $serviceName := include "java-app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ing
  labels:
{{ include "java-app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /status
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
        {{- end }}
  {{- end }}
